### ISSUE TITLE
IOU 

### ISSUE THREAD

**Issue by tongyihang** [brdav/cma#3]
hello, Where are the IOU indicators displayed for each category. thank

**Comment by brdav** [comment]
I only return the mIoU in the released code. To obtain per-class IoU, you should pass `average=none` to the helpers.metrics.IoU class, see https://lightning.ai/docs/torchmetrics/stable/classification/jaccard_index.html#torchmetrics.classification.MulticlassJaccardIndex
You will then have to slightly adapt how you log the metrics in 
https://github.com/brdav/cma/blob/41838718481ec8db9c3c11acfe53f62a00630d24/models/model.py#L186
since the metrics will return an array of length `n_classes` instead of a single number.
